# -*- coding: utf-8 -*-
"""ai no 07000

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nElUhVjy0WBJQ0Kb6ROUpFlidgbJ0SfZ
"""

!pip install ai-edge-litert

# ===============================================
# 🧠 Emotion Detector (Text + Image) in Google Colab
# ===============================================

# --- STEP 1: Install required libraries ---
!pip install -q transformers torch fer opencv-python Pillow gradio

# --- STEP 2: Import libraries ---
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from fer.fer import FER
import cv2
import numpy as np
from PIL import Image
import gradio as gr

# --- STEP 3: Load Models ---

# Load text emotion model (GoEmotions-based)
TEXT_MODEL_NAME = "j-hartmann/emotion-english-distilroberta-base"

tokenizer = AutoTokenizer.from_pretrained(TEXT_MODEL_NAME)
text_model = AutoModelForSequenceClassification.from_pretrained(TEXT_MODEL_NAME)
device = "cuda" if torch.cuda.is_available() else "cpu"
text_model.to(device)

# FER model for facial emotion detection
face_emotion = FER(mtcnn=False) # Changed mtcnn=True to mtcnn=False

# --- STEP 4: Define Functions ---

def analyze_text_emotion(text):
    """Detect emotions from text input"""
    if not text.strip():
        return {"Error": "Please enter some text."}

    inputs = tokenizer(text, truncation=True, padding=True, return_tensors="pt").to(device)
    with torch.no_grad():
        outputs = text_model(**inputs)
        probs = torch.softmax(outputs.logits, dim=-1)[0].cpu().numpy()

    id2label = text_model.config.id2label
    results = sorted([(id2label[i], float(p)) for i, p in enumerate(probs)], key=lambda x: x[1], reverse=True)
    results_text = "\n".join([f"{label}: {score:.3f}" for label, score in results[:6]])
    return results_text


def analyze_image_emotion(image):
    """Detect emotions from face image"""
    if image is None:
        return "Please upload an image."

    image_np = np.array(image.convert("RGB"))
    result = face_emotion.detect_emotions(image_np)
    if not result:
        return "No face detected."

    # Aggregate emotions from all faces
    emotions = {}
    for face in result:
        for k, v in face['emotions'].items():
            emotions[k] = emotions.get(k, 0) + v
    for k in emotions:
        emotions[k] /= len(result)

    sorted_emotions = sorted(emotions.items(), key=lambda x: x[1], reverse=True)
    output = "\n".join([f"{label}: {score:.3f}" for label, score in sorted_emotions[:6]])
    return output


# --- STEP 5: Build Gradio Interface ---
text_interface = gr.Interface(
    fn=analyze_text_emotion,
    inputs=gr.Textbox(lines=4, placeholder="Type a sentence here..."),
    outputs="text",
    title="🧠 Text Emotion Detector",
    description="Detect emotions such as anger, sadness, joy, fear, disgust, etc. from text."
)

image_interface = gr.Interface(
    fn=analyze_image_emotion,
    inputs=gr.Image(type="pil"),
    outputs="text",
    title="📸 Image Emotion Detector",
    description="Upload a human face to detect emotions like happiness, anger, sadness, etc."
)

# Combine into one tabbed UI
app = gr.TabbedInterface([text_interface, image_interface], ["Text Emotion", "Image Emotion"])

# --- STEP 6: Launch UI ---
app.launch(share=True)